version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
